# Generated by Django 4.2 on 2023-04-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profiletable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pic')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='table',
            old_name='discrip',
            new_name='desc',
        ),
    ]
